### ISSUE TITLE
support config file

### ISSUE THREAD

**Issue by forkwhilefork** [forkwhilefork/rss2email#6]
Instead of running a command to add an rss feed, read it from a config file. Also maybe from the DB once that's implemented.

**Comment by forkwhilefork** [comment]
This would allow different sending settings per feed, too.

example in YAML:
```
---
configs:
- feeds:
  - https://example.com/feed
  - https://example.com/feed2
  - https://example.com/feed3
  send: true
  useSendy: true
  usePushover: true
- feeds:
  - https://example2.com/feed
  - https://example2.com/feed2
  - https://example2.com/feed3
  send: true
  useSendy: false
  usePushover: true
- feeds:
  - https://example3.com/feed
  - https://example3.com/feed2
  - https://example3.com/feed3
  send: true
  useSendy: true
  usePushover: false
```


(obv missing most settings but you get the idea)
